sudo: false
dist: trusty
language: node_js
git:
  depth: 3
cache:
  directories:
  - node_modules
node_js:
- 8.4.0
before_script:
- npm prune
script:
- npm run ci
after_success:
- cd build
- npm i
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
notifications:
  email:
    on_success: change
    on_failure: change
