sudo: false
dist: trusty
language: node_js
git:
  depth: 3

cache:
  directories:
  - node_modules

node_js:
  - '7.6.0'

before_script:
  - npm prune
script:
  - npm run ci
after_success:
  - cp package.json build/
  - cd build
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email:
    on_success: change
    on_failure: change
